### ISSUE TITLE
AssertionError ? 

### ISSUE THREAD

**Issue by jtoy** [seangal/dcgan_vae_pytorch#3]
im testing on a simple dataset with 2 classes:
python main.py --dataset=folder --dataroot=/data/vae_images/ --imageSize=256 --cuda
I get the error:
Traceback (most recent call last):
```
  File "main.py", line 291, in <module>
    errD_real = criterion(output, label)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 36, in forward
    return backend_fn(self.size_average, weight=self.weight)(input, target)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/thnn/loss.py", line 22, in forward
    assert input.nelement() == target.nelement()

```

Any idea how to fix this or why it is happening?

**Comment by seangal** [comment]
Currently, the networks support only `--imageSize=64` but I will fix it in the next hour..

**Comment by seangal** [comment]
This should be fixed. Update me if you have any problems

**Comment by jtoy** [comment]
it trains on 256 size images,  thanks
